#!/bin/sh

red=255
green=0
blue=0

inc_gradient() {
	i=0
	while [ "$i" -lt 255 ]; do
		printf '\033[48;2;%d;%d;%dm ' $red $green $blue
		eval "$1=\$(($1 + 1))"
		i=$((i + 1))
	done
}

dec_gradient() {
	i=0
	while [ "$i" -lt 255 ]; do
		printf '\033[48;2;%d;%d;%dm ' $red $green $blue
		eval "$1=\$(($1 - 1))"
		i=$((i + 1))
	done
}

iters=${1:-1}
while [ "$iters" -gt 0 ]; do
	inc_gradient green # -> yellow
	dec_gradient red   # -> green
	inc_gradient blue  # -> cyan
	dec_gradient green # -> blue
	inc_gradient red   # -> purple
	dec_gradient blue  # -> red
	iters=$((iters - 1))
done
printf '\033[0m\n'
