#!/bin/sh

FG_WHITE=97
FG_BLACK=30

col=0
stop=16
while [ $col -lt $stop ]; do
	fg=$FG_WHITE
	[ $col -ge 8 ] && fg=$FG_BLACK
	[ $col -eq 8 ] && printf '          ' # manually alignment deadass
	printf '\033[%d;48;5;%dm   %s   \033[0m ' $fg $col $col
	col=$((col + 1))
done

printf '\n'

col=16
stop=232
while [ $col -lt $stop ]; do
	i=$((col - 16))
	fg=$FG_WHITE
	[ $((i / 18 % 2)) -eq 1 ] && fg=$FG_BLACK
	[ $((i % 36)) -eq 0 ] && printf '\n'
	printf '\033[%d;48;5;%dm%3s\033[0m ' $fg $col $col
	col=$((col + 1))
done

printf '\n\n'

col=232
stop=256
while [ $col -lt $stop ]; do
	fg=$FG_WHITE
	[ $col -gt 243 ] && fg=$FG_BLACK
	printf '\033[%d;48;5;%dm %s \033[0m ' $fg $col $col
	col=$((col + 1))
done

printf '\n'
