#!/bin/sh

# I call it the *Semver charset + underscore* as it contains all the allowed
# characters that one would find in a semver string with underscore included.

find "$@" -not -regex '.*/[a-zA-Z0-9._+-]*'
