#!/usr/bin/env python3

import argparse as argparse
import io as io
import os as os


def highlight(fp: io.TextIOWrapper) -> None:
    RESET = '\033[0m'
    BLACK = '\033[90m'
    RED_BOLD = '\033[1;91m'

    while (row := fp.readline()) != '':
        row = row.rstrip('\n')
        row_len = len(row)
        bad_idxs = []

        for idx in range(row_len):
            left = row[idx]
            right = row[-1 - idx]

            if left != right or idx in bad_idxs:
                print(f'{RED_BOLD}{left}{RESET}', end='')
                bad_idxs.append(row_len - 1 - idx)
            else:
                print(f'{BLACK}{left}{RESET}', end='')
        print()


def check(fp: io.TextIOWrapper) -> bool:
    while (row := fp.readline()) != '':
        row = row.rstrip('\n')

        for idx in range(len(row)):
            left = row[idx]
            right = row[-1 - idx]

            if left != right:
                return False
    return True


if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description='Highlight unsymmetric parts of a file.'
    )
    parser.add_argument('file', help='file to highlight', type=str)
    parser.add_argument(
        '-q', '--quiet', help="don't output anything", action='store_true'
    )

    args = parser.parse_args()
    file = args.file
    is_quiet = args.quiet

    if not os.path.exists(file):
        parser.error('file was not found')
        exit(1)
    if not os.path.isfile(file):
        parser.error('file is not a regular file')
        exit(1)

    with open(file, 'r') as fp:
        if is_quiet:
            exit(0 if check(fp) else 1)
        else:
            highlight(fp)
