#!/bin/sh

# I couldn't come up with something better. This will spawn a bunch of PIDs...

find "$@" \
	-regextype posix-extended \
	-regex '(.*/)?[^/]*\.git' -prune -or \
	-name 'site-packages' -prune -or \
	-name 'node_modules' -prune -or \
	-type f -and -not -exec sh -c 'test "$(tail -c 1 "$1")" = ""' -- '{}' \; -print
