#!/bin/sh

find "$@" \
	-regextype posix-extended \
	-name '*.git' -prune -o \
	-name site-packages -prune -o \
	-name node_modules -prune -o \
	-name target -prune -o \
	\! -regex '(.*/)?(\.|__?)?[a-zA-Z0-9][a-zA-Z0-9._+-]*' -print
