#!/bin/sh

find "$@" \
	-regextype posix-extended \
	-name '*.git' -prune -o \
	-name site-packages -prune -o \
	-name node_modules -prune -o \
	-name target -prune -o \
	\( \( -type d \! -perm 0755 \) -o \
	\( -type f \! \( -perm 0644 -o -perm 0755 \) \) \) -exec stat -c '%a: %n: %F' '{}' +
