#!/bin/sh

# FIXME: I don't know if this work lol

# Find files while respecting ignore files

set -eu

dir=$(realpath "$1")/

cat "$dir/.ignore" 2>/dev/null || :
cat "$dir/.gitignore" 2>/dev/null || :
cat "$dir/.git/info/exclude" 2>/dev/null || :

for file in "$dir"/* "$dir"/.[!.]*; do
	printf '%-20s: ' "${file##"$dir"}"

	grep -qsx "${file##"$dir"}" \
		"$dir/.ignore" \
		"$dir/.gitignore" \
		"$dir/.git/info/exclude" &&
		echo "ignore" && continue

	if [ -d "$file" ]; then
		echo "recurse"
	else
		echo "print"
	fi
done

# '.'
# '..'
# '.[!.]*'
# '*.git'
