#!/bin/sh

notify-send -u critical 'Test message: critical test 1' 'Summary aaa bbb ccc'
notify-send -u normal 'Test message: normal test 2' 'Summary ddd eee fff'
notify-send -u low 'Test message: low test 3' 'Summary ggg hhh iii'

notify-send -u critical 'Test message: critical test 4'
notify-send -u normal 'Test message: normal test 5'
notify-send -u low 'Test message: low test 6'

notify-send -u critical 'Test message: critical test 7' 'Summary rrr sss ttt'
notify-send -u normal 'Test message: normal test 8' 'Summary uuu vvv www'
notify-send -u low 'Test message: low test 9' 'Summary xxx yyy zzz'
